#!/data/data/com.termux/files/usr/bin/bash

P10K_CONFIG="$HOME/.p10k.zsh"

apply_frame() {
    sed -i "s|typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=.*|typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%240F$1'|" "$P10K_CONFIG"
    sed -i "s|typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=.*|typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='%240F$2'|" "$P10K_CONFIG"
    sed -i "s|typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=.*|typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%240F$3'|" "$P10K_CONFIG"
    
    rm -rf "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"* 2>/dev/null
    
    echo -e "\033[1;32mFrame swapped.\033[0m"
    echo -e "\033[1;33mRestart Termux to apply.\033[0m"
}

choice=$(echo -e "Rounded\nMinimal\nHeavy\nDots" | fzf --prompt="Select Frame > " --height=40% --reverse --border)

case "$choice" in
    "Rounded") apply_frame "╭─" "├─" "╰─" ;;
    "Minimal") apply_frame "┌─" "├─" "└─" ;;
    "Heavy") apply_frame "┏━" "┣━" "┗━" ;;
    "Dots") apply_frame "┊ " "┊ " "╰─" ;;
esac
