#!/data/data/com.termux/files/usr/bin/bash

R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
C="$(printf '\033[1;36m')"
NC="$(printf '\033[0m')"

FONT_TO_DOWNLOAD=$1
readonly TERMUX_HOME=${HOME:-/data/data/com.termux/files/home}

function print_msg() {
	local msg
	msg="$1"
	echo "${R}[${C}-${R}]${G} $msg ${NC}"
}

function check_and_create_directory() {
	if [[ -n "$1" && ! -d "$1" ]]; then
		mkdir -p "$1"
	fi
}

function print_success() {
	local msg
	msg="$1"
	echo "${R}[${G}✓${R}]${G} $msg ${NC}"
}

function print_failed() {
	local msg
	msg="$1"
	echo "${R}[${R}☓${R}]${R} $msg ${NC}"
}

function check_and_delete() {
	local files_folders
	for files_folders in "$@"; do
		if [[ -e "$files_folders" ]]; then
			rm -rf "$files_folders" >/dev/null 2>&1
		fi
	done
}

function select_an_option() {
	local max_options=$1
	local default_option=${2:-1}
	local response_var=$3
	local response

	while true; do
		read -r -p "${Y}select an option (Default ${default_option}): ${NC}" response
		response=${response:-$default_option}

		if [[ $response =~ ^[0-9]+$ ]] && ((response >= 1 && response <= max_options)); then
			echo
			print_success "Continuing with answer: $response"
			sleep 0.2
			eval "$response_var=$response"
			break
		else
			echo
			print_failed " Invalid input, Please enter a number between 1 and $max_options"
		fi
	done
}

function download_file() {
	local dest
	local url
	local max_retries=5
	local attempt=1
	local successful_attempt=0

	if [[ -z "$2" ]]; then
		url="$1"
		dest="$(basename "$url")"
	else
		dest="$1"
		url="$2"
	fi

	if [[ -z "$url" ]]; then
		print_failed "No URL provided!"
		return 1
	fi

	while [[ $attempt -le $max_retries ]]; do
		print_msg "Downloading $dest..."
		if [[ ! -s "$dest" ]]; then
			check_and_delete "$dest"
		fi

		if command -v wget &>/dev/null; then
			wget --tries=5 --timeout=15 --retry-connrefused -O "$dest" "$url"
		else
			curl -# -L "$url" -o "$dest"
		fi

		if [[ -f "$dest" && -s "$dest" ]]; then
			successful_attempt=$attempt
			break
		else
			print_failed "Download failed. Retrying... ($attempt/$max_retries)"
		fi
		((attempt++))
	done

	if [[ -f "$dest" ]]; then
		return 0
	fi
	return 1
}

function extract_archive() {
	local archive="$1"
	if [[ ! -f "$archive" ]]; then
		print_failed "$archive doesn't exist"
	fi

	case "$archive" in
	*.tar.gz | *.tgz | *.tar.xz)
		print_success "Extracting ${C}$archive"
		tar xvf "$archive" || return 1
		;;
	*.zip)
		print_success "Extracting ${C}$archive"
		unzip "${archive}" || return 1
		;;
	*)
		print_failed "Unsupported format: ${C}$archive"
		return 1
		;;
	esac
}

function download_and_extract() {
	local url="$1"
	local target_dir="$2"
	local filename="${url##*/}"

	if [[ -n "$target_dir" ]]; then
		check_and_create_directory "$target_dir"
		cd "$target_dir" || return 1
	fi

	if download_file "$filename" "$url"; then
		extract_archive "$filename"
		check_and_delete "$filename"
	fi
}

function get_latest_release() {
	curl -s "https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
}

function download_and_install_font() {
	latest_nf_version=$(get_latest_release "ryanoasis" "nerd-fonts")

	if [[ -z $FONT_TO_DOWNLOAD ]]; then
        print_msg "Installing default Meslo..."
        sel_base_name="Meslo"
	else
		sel_base_name="$FONT_TO_DOWNLOAD"
	fi

	download_and_extract "https://github.com/ryanoasis/nerd-fonts/releases/download/${latest_nf_version}/${sel_base_name}.tar.xz" "$TERMUX_HOME/.fonts"

	nerd_font_file=$(find "$TERMUX_HOME/.fonts" -type f \( -iname "${sel_base_name}*Regular.ttf" -o -iname "${sel_base_name}*Regular.otf" \) | head -n1)

	if [[ -n "$nerd_font_file" ]]; then
		check_and_create_directory "$TERMUX_HOME/.termux"
		cp "$nerd_font_file" "$TERMUX_HOME/.termux/font.ttf"
		fc-cache -fv >/dev/null 2>&1
        am broadcast --user 0 -a com.termux.app.reload_style com.termux >/dev/null 2>&1
		termux-reload-settings
        print_success "SYSTEM REWIRED: $sel_base_name ACTIVE."
	else
		print_failed "INJECTION FAILED: $sel_base_name NOT FOUND."
	fi
}

cd "$TERMUX_HOME" || exit 1
download_and_install_font
