#!/data/data/com.termux/files/usr/bin/bash

C_RED='\033[1;31m'
C_GRN='\033[1;32m'
C_YEL='\033[1;33m'
C_RST='\033[0m'

clear
echo -e "${C_YEL}This is going to delete the entire Zsh setup and all custom tools.${C_RST}"
read -p "Are you sure? (y/n): " confirm
[[ "$confirm" != "y" ]] && exit 0

echo -e "${C_RED}[-] Removing configuration files...${C_RST}"
rm -f ~/.zshrc ~/.zshenv ~/.p10k.zsh ~/.nanorc ~/.hushlogin ~/.termux_user
rm -f ~/motd.sh ~/ninja.sh

echo -e "${C_RED}[-] Cleaning up directories...${C_RST}"
rm -rf ~/.termux/ascii ~/.termux/icons ~/.termux/current_art.txt ~/.termux/motd_style
rm -rf ~/.config/fastfetch ~/.local/share/zinit ~/.cache/p10k-instant-prompt-*

echo -e "${C_RED}[-] Deleting custom binaries...${C_RST}"
for bin in termux-nf seticon setframe setpill kawai beam warp peek scrub host amv ftext snatch tssh setrepo gfix setmotd termux-color uninstall-myzsh; do
    rm -f "$PREFIX/bin/$bin"
done

echo -e "${C_RED}[-] Resetting terminal properties...${C_RST}"
rm -f ~/.termux/termux.properties ~/.termux/colors.properties ~/.termux/font.ttf

echo -e "${C_YEL}[!] Switching shell back to Bash...${C_RST}"
chsh -s bash

echo -e "${C_GRN}[+] Done. Everything is gone. Restart Termux to see the default look.${C_RST}"
